Cliente_ProyectoFinal/Controllers/CreditoController.cs
using Microsoft.AspNetCore.Mvc;
using Cliente_ProyectoFinal.Servicios;
using Cliente_ProyectoFinal.Models.Credito;
using System.Security.Cryptography.X509Certificates;
using ClosedXML.Excel;
using System.Data;


namespace Cliente_ProyectoFinal.Controllers
{

    [ServiceFilter(typeof(class_VerificarTokenFiltro))]

    public class CreditoController : Controller
    {


        private readonly class_CreditoServicio _creditoService;

        public CreditoController(class_CreditoServicio creditoService)
        {
            _creditoService = creditoService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                Response.Headers["Cache-Control"] = "no-store, no-cache, must-revalidate, private";
                Response.Headers["pragma"] = "no-cache";
                Response.Headers["Expires"] = "-1";

                string token = HttpContext.Session.GetString("Token");

                List<Class_Credito> creditos = await _creditoService.ObtenerCreditoAsync(token);

                return View( creditos);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al obtener los creditos");
                return View(new List<Class_Credito>());
            }
        }

        [HttpPost]
        public async Task<IActionResult> BuscarCredito(string CedulaP)
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                var creditos = await _creditoService.BuscarCreditoAsync(CedulaP, token);

                if (creditos == null || creditos.Count == 0)
                {
                    ViewBag.Mensaje = "No se encontraron créditos con esa cédula.";
                }

                return View(creditos);
            }
            catch
            {
                ViewBag.Mensaje = "Ocurrió un error al buscar los créditos.";
                return View( new List<Class_Credito>());
            }
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Class_Credito credito)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("Token");
                credito.fecha_creacion = DateTime.Now;
                credito.estado = "Activo";

                var mensajeError = await _creditoService.CrearCreditoAsync(credito, token);

                if (mensajeError == null)
                {
                    TempData["Mensaje"] = "Crédito creado exitosamente.";
                    return RedirectToAction("Index");
                }
                else
        {
                    ModelState.AddModelError("", mensajeError);
                }
            }

            return View(credito);
        }
       


        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            string token = HttpContext.Session.GetString("Token");
            var credito = await _creditoService.BuscarCreditoPorIdAsync(id, token);
            if (credito == null) return NotFound();
            return View(credito);
        }


        [HttpPost]
        public async Task<IActionResult> Editar(int id, Class_Credito credito)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("Token");
                await _creditoService.ActualizarCreditoAsync(id, credito, token);
                //return RedirectToAction(nameof(Index));
                TempData["Mensaje"] = "Crédito creado exitosamente.";
                return RedirectToAction("Index");
            }
            return View(credito);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                bool eliminado = await _creditoService.EliminarCreditoAsync(id, token);

                if (eliminado)
                {
                    TempData["Mensaje"] = "Crédito eliminado exitosamente.";
                }
                else
                {
                    TempData["Mensaje"] = "No se pudo eliminar el crédito.";
                }
            }
            catch
            {
                TempData["Mensaje"] = "Ocurrió un error al intentar eliminar el crédito.";
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> ExportarExcel()
        {
            string token = HttpContext.Session.GetString("Token");
            var listaCreditos = await _creditoService.ObtenerCreditoAsync(token);

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Créditos");

                // Encabezados
                worksheet.Cell(1, 1).Value = "ID";
                worksheet.Cell(1, 2).Value = "Cédula";
                worksheet.Cell(1, 3).Value = "Monto Máximo";
                worksheet.Cell(1, 4).Value = "Saldo Actual";
                worksheet.Cell(1, 5).Value = "Fecha Creación";
                worksheet.Cell(1, 6).Value = "Fecha Vencimiento";
                worksheet.Cell(1, 7).Value = "Estado";

                int fila = 2;
                foreach (var credito in listaCreditos)
                {
                    worksheet.Cell(fila, 1).Value = credito.credito_ID;
                    worksheet.Cell(fila, 2).Value = credito.Cedula_P;
                    worksheet.Cell(fila, 3).Value = credito.monto_maximo;
                    worksheet.Cell(fila, 4).Value = credito.saldo_actual;
                    worksheet.Cell(fila, 5).Value = credito.fecha_creacion?.ToString("yyyy-MM-dd");
                    worksheet.Cell(fila, 6).Value = credito.fecha_vencimiento?.ToString("yyyy-MM-dd");
                    worksheet.Cell(fila, 7).Value = credito.estado;
                    fila++;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    stream.Position = 0;
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "ReporteCreditos.xlsx");
                }
            }
        }






    }
}

Cliente_ProyectoFinal/Controllers/OcupacionController.cs
using Microsoft.AspNetCore.Mvc;
using Cliente_ProyectoFinal.Servicios;
using System.Security.Cryptography.X509Certificates;
using Cliente_ProyectoFinal.Models.Ocupaciones;

namespace Cliente_ProyectoFinal.Controllers
{
    [ServiceFilter(typeof(class_VerificarTokenFiltro))]
    public class OcupacionController : Controller
    {

        private readonly Class_OcupacionServicio _OcupacionService;

        public OcupacionController(Class_OcupacionServicio OcupacionService)
        {
            _OcupacionService = OcupacionService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                Response.Headers["Cache-Control"] = "no-store, no-cache, must-revalidate, private";
                Response.Headers["pragma"] = "no-cache";
                Response.Headers["Expires"] = "-1";

                string token = HttpContext.Session.GetString("Token");

                List<Class_Ocupaciones> creditos = await _OcupacionService.ObtenerOcupacionesAsync(token);

                return View(creditos);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al obtener los creditos");
                return View(new List<Class_Ocupaciones>());
            }
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Class_Ocupaciones habi)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("Token");


                var mensajeError = await _OcupacionService.CrearOcupacionnAsync(habi, token);

                if (mensajeError == null)
                {
                    TempData["Mensaje"] = "ocupacion creada exitosamente.";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", mensajeError);
                }
            }

            return View(habi);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                bool eliminado = await _OcupacionService.EliminarOcupacionAsync(id, token);

                if (eliminado)
                {
                    TempData["Mensaje"] = "Ocupación eliminada correctamente.";
                }
                else
                {
                    TempData["Error"] = "No se pudo eliminar la ocupación.";
                }
            }
            catch
            {
                TempData["Error"] = "Ocurrió un error al eliminar la ocupación.";
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            string token = HttpContext.Session.GetString("Token");

            var ocupacion = await _OcupacionService.BuscarOcupacionPorIdAsync(id, token);
            if (ocupacion == null)
                return NotFound();

            return View(ocupacion);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Class_Ocupaciones ocupacion)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("Token");
                var exito = await _OcupacionService.ActualizarOcupacionAsync(id, ocupacion, token);

                if (exito)
                {
                    TempData["Mensaje"] = "Ocupación actualizada correctamente.";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "No se pudo actualizar la ocupación.");
                }
            }

            return View(ocupacion);
        }

    }
}

Cliente_ProyectoFinal/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Cliente_ProyectoFinal.Servicios;
using Cliente_ProyectoFinal.Models.Usuario;
using System.Security.Cryptography.X509Certificates;
using Cliente_ProyectoFinal.Models.Ocupaciones;
using Microsoft.AspNetCore.Mvc.Rendering;



namespace Cliente_ProyectoFinal.Controllers
{
    [ServiceFilter(typeof(class_VerificarTokenFiltro))]

    public class UsuarioController : Controller
    {
        private readonly Class_PersonaServicio _personaService;

        public UsuarioController(Class_PersonaServicio personaService)
        {
            _personaService = personaService;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                List<class_User> personas = await _personaService.ObtenerPersonasAsync(token);
                return View(personas);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error al obtener los creditos");
                return View(new List<class_User>());
            }
        }

        [HttpPost]
        public async Task<IActionResult> BuscarUsuario(string CedulaP)
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                var persona = await _personaService.BuscarPersonaAsync(CedulaP, token);

                if (persona == null)
                {
                    ViewBag.Mensaje = "No se encontro datos de esta persona";
                }

                return View("Persona");
            }
            catch
            {
                ViewBag.Mensaje = "Ocurrió un error al buscar los datos de la persona.";
                return View("", new List<class_User>());
            }
        }

        
        [HttpGet]
        public IActionResult Crear()
        {
            ViewBag.Roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Administrador", Value = "1" },
        new SelectListItem { Text = "Empleado", Value = "2" },
        new SelectListItem { Text = "Cliente", Value = "3" }
    };

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(class_User habi)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("Token");


                var mensajeError = await _personaService.CrearPersonaAsync(habi, token);

                if (mensajeError == null)
                {
                    TempData["Mensaje"] = "ocupacion creada exitosamente.";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", mensajeError);
                }
            }
            ViewBag.Roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Administrador", Value = "1" },
        new SelectListItem { Text = "Empleado", Value = "2" },
        new SelectListItem { Text = "Cliente", Value = "3" }
    };

            return View(habi);
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            try
            {
                string token = HttpContext.Session.GetString("Token");
                bool eliminado = await _personaService.EliminarUsuarioAsync(id, token);

                if (eliminado)
                {
                    TempData["Mensaje"] = "Ocupación eliminada correctamente.";
                }
                else
                {
                    TempData["Error"] = "No se pudo eliminar la ocupación.";
                }
            }
            catch
            {
                TempData["Error"] = "Ocurrió un error al eliminar la ocupación.";
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Editar(string id)
        {
            string token = HttpContext.Session.GetString("Token");

            var persona = await _personaService.BuscarPersonaPorCedulaAsync(id, token);
            if (persona == null)
                return NotFound();

            ViewBag.Roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Administrador", Value = "1" },
        new SelectListItem { Text = "Empleado", Value = "2" },
        new SelectListItem { Text = "Cliente", Value = "3" }
    };

            return View(persona);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(String id, class_User persona)
        {
            if (ModelState.IsValid)
            {

                string token = HttpContext.Session.GetString("Token");
                var exito = await _personaService.ActualizarPersonaAsync(id, persona, token);

                if (exito)
                {
                    TempData["Mensaje"] = "Persona actualizada correctamente.";
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("", "No se pudo actualizar la persona.");
            }
                ViewBag.Roles = new List<SelectListItem>
    {
        new SelectListItem { Text = "Administrador", Value = "1" },
        new SelectListItem { Text = "Empleado", Value = "2" },
        new SelectListItem { Text = "Cliente", Value = "3" }
    };

            

            return View(persona);
        }

    }
}

Cliente_ProyectoFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cliente_ProyectoFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cliente_ProyectoFinal.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #455A64">
    <header style="background-color: #eeebe5;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/images/logo.png" alt="Resigest Logo" style="height: 60px; margin-right: 10px;" class="me-auto" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Credito" asp-action="Index">Creditos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MovimientoCredito" asp-action="Index">MovimientoCredito</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Habitaciones" asp-action="Index">Habitaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ocupacion" asp-action="Index">Ocupaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                        </li>
                    </ul>

                    <!-- Botón de cerrar sesión alineado a la derecha -->
                    <form asp-controller="Autenticacion" asp-action="Logout" method="post" class="d-flex ms-auto">
                        <button type="submit" class="btn btn-danger btn-sm">Cerrar Sesión</button>
                    </form>
                        
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Cliente_ProyectoFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Cliente_ProyectoFinal/Views/Shared/_layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cliente_ProyectoFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cliente_ProyectoFinal.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #455A64">
    <header style="background-color: #eeebe5;">
        <nav class="navbar navbar-light border-bottom box-shadow mb-3">
            <div class="container justify-content-center">
                <img src="~/images/logo.png" alt="Resigest Logo" style="height: 60px;" class="me-auto" />

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>